//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client Memcached backed Proxy/Service Ticket Managers")]
[assembly: AssemblyDescription("Memcached backed Proxy/Service Ticket Managers for the Apereo .NET CAS Client")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client Memcached backed Proxy/Service Ticket Managers")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2018 Apereo.  All rights reserved.")]

