//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Apereo .NET CAS Client Memcached backed Proxy/Service Ticket Managers")]
[assembly: AssemblyDescription("Memcached backed Proxy/Service Ticket Managers for the Apereo .NET CAS Client.")]
[assembly: AssemblyCompany("Apereo Foundation")]
[assembly: AssemblyProduct("Apereo .NET CAS Client Memcached backed Proxy/Service Ticket Managers")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-unstable.9+Branch.develop.Sha.62490d364967bd45f692f91e8cbce831795a8f33")]
[assembly: AssemblyCopyright("Copyright (c) 2007-2018 Apereo.  All rights reserved.")]

